# APP请求日志存储配置
logging:
  path: /data/logs/app_logs
  file: mall-msg
  config: classpath:logback-spring.xml

super:
  ip: "${yun.super.ip}"

server:
  port: 8097
  context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 30000

spring:
  session:
    store-type: none
  sleuth:
    sampler:
      percentage: 1.0
  # Redis连接配置
  redis:
    # Redis服务器地址
    host: "${yun.redis.host}"
    # Redis服务器端口
    port: "${yun.redis.port}"
    # 连接超时时间（毫秒）
    timeout: 0
    #Redis数据库索引
    database: 0
    # Redis服务器连接密码（默认为空）
    password: "${yun.redis.password}"
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
  # 大数据统计Redis连接配置

################################
#rest:
#  connection:
#    connection-request-timeout: 5000
#    connect-timeout: 5000
#    read-timeout: 30000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 5000

################################生产环境配置，请勿修改###########################


